[BOT-XYZ]fix custom greetings messages
vostpt/bot pull request #294
Opened 2024-01-03 02:00 UTC by MicaelMCarvalho

## Description
This pull request addresses issue [BOT-XYZ](https://github.com/vostpt/bot/issues/XYZ).

## Task items:
- [ ] Fixed issue X;
- [ ] Added feature Y;
- [ ] Updated the documentation for Z;
- [ ] Increased test coverage for W;
- [ ] Other task related item;
- [ ] ...

## Requirements (optional)
Requirements when deploying the current work to an environment (`dev`, `staging` or `production`):

- An `ENV` variable needs to be added;
- Permissions need to be set for `X`, `Y` and `Z`;
- ...

2024-01-07 00:49 UTC, MicaelMCarvalho commented
@JorgeMiguelGomes ou @miguelcarreiro  podem verificar este PR. Fiz teste no discord e funciona.

2024-01-07 09:49 UTC, JorgeMiguelGomes requested changes
User 401531455832064010 message should be 
"Agora que não podes beber café toma lá um descafeinado... yuck!"

2024-01-07 12:33 UTC, miguelantoniosantos submitted a review, later dismissed
Code wise lgtm

2024-01-07 22:29 UTC, MicaelMCarvalho commented
done @JorgeMiguelGomes

2024-07-01 18:11 UTC, MicaelMCarvalho commented
@JorgeMiguelGomes podes fazer merge? Ou já voltaste a beber café :)

2024-07-08 08:10 UTC, JorgeMiguelGomes commented
> @JorgeMiguelGomes podes fazer merge? Ou já voltaste a beber café :)

Penso que temos que fazer mais modificações, porque o Torres, por exemplo bebe chá, e estava a funcionar antes do Discord ter vindo com esta coisa dos usernames. Qual será a melhor maneira de fazer isso?

2024-07-08 09:35 UTC, MicaelMCarvalho commented
Boas @JorgeMiguelGomes
Eu converti os antigos ids para os novos e o Torres já lá está, é o id 501025896732426250

Se quiseres verificar a lista, a forma mais fácil de ver o id de um utilizador é o seguinte:
- Discord Settings > Advanced > Turn on Developer Name
- Right Click on user and last option "Copy User ID" 
Este ID é o que precisa de estar na lista

2024-07-08 10:54 UTC, JorgeMiguelGomes approved these changes

2024-07-08 10:55 UTC, merged

2024-07-08 10:55 UTC, JorgeMiguelGomes commented
Done