Feature/twitter/image tweet
vostpt/bot pull request #55
Opened 2019-05-12 19:10 UTC by J0N4S13

## Description
Image upload code in twitter commented, in the future send a gif instead of a png.

## Task items:
- [ ] Image upload code on twitter commented;

2019-05-12 21:56 UTC, quetzyg requested changes
Left some comments.

2019-05-12 21:56 UTC, quetzyg commented on src/services/Warnings.js
> +// const fs = require('fs');
If the code isn't required, just remove it.

2019-05-12 21:56 UTC, quetzyg commented on src/services/Warnings.js
> +      // Review the code to send GIF
Same as above, commented code shouldn't be committed.

2019-05-12 21:56 UTC, quetzyg commented on src/services/Warnings.js
> +          console.log(error);
Also, avoid the use of `console.log()`

2019-06-15 22:54 UTC, miguelcarreiro commented
I think that this PR should be closed, since this feature was already implemented in PR https://github.com/vostpt/bot/pull/72

2019-06-17 15:27 UTC, closed without merging