Fix/earthquakes/schedule
vostpt/bot pull request #56
Opened 2019-05-12 19:13 UTC by J0N4S13

## Description
Send a message to the earthquake discord in the last 10 minutes, if there was any earthquake felt in that time or if there was any earthquake with more than 3 magnitude.

## Task items:
- [ ] Add schedule code;
- [ ] Add a code in Earthquakes.js in services;

2019-05-12 22:01 UTC, quetzyg requested changes
Left some comments.

2019-05-12 22:01 UTC, quetzyg commented on src/services/Earthquakes.js
> +    //
What's the point of this catch?

2019-05-12 22:01 UTC, quetzyg commented on src/services/Earthquakes.js
> +    } else if (magnitud >= 3) {
`magnitud` -> `magnitude`

2019-05-12 22:01 UTC, quetzyg commented on src/services/Earthquakes.js
> +  } catch (e) {
You might as well remove the whole try/catch, since this just throws what gets caught. Let it bubble up.

2019-06-18 08:19 UTC, tiagojpdias commented
Closing due to inactivity.

2019-06-18 08:19 UTC, closed without merging